### ISSUE TITLE
TODO: Fix EmptyPacket Handling during Auth Phase

### ISSUE THREAD

**Issue by Sufod** [Sufod/Gofus#13]
https://github.com/Sufod/Gofus/blob/992eaeef97aa6a6db94ffaf1cbf87141ca53f1f1/internal/client/handlers/auth_phase/auth_handler.go#L73

**Comment by nextrie** [comment]
Done, 
		`authHandler.handleUsername() //Ad + username`

		authHandler.handleEmptyPacket() //Ac2

		authHandler.handleServerList() //AH + servers

		authHandler.handleEmptyPacket() //AlK

		authHandler.handleEmptyPacket() //AQ

		authHandler.selectServer()

		authHandler.connectToGameServer()
